### ISSUE TITLE
Particles for certain decorations aren't loading (purple)

### ISSUE THREAD

**Issue by MagmaFang23** [AbsoluteStratos/ChristmasInDirtmouth#1]
Hello! Came across this while browsing through "What's New" on Lumafly, and I just want to say, this is a really nice and cute little mod! Now, after installing it and buying the candles (disclaimer, I have not tested any other of the decorations yet!), the particles emitted by the candles have an error texture.
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/5d5f7ca1-e39b-4fce-b5db-d97b8d827b1c" />

**Comment by AbsoluteStratos** [comment]
Thanks for opening an issue, let me see if I can replicate. 🤔 

Youre on windows? Any other mods installed?

**Comment by MagmaFang23** [comment]
I'm on a Mac, unfortunately. 
Other mods include (ruling out Vocalised):
Benchwarp (including BenchWarpFix)
Custom Knight
DebugMod
Enemy HP Bar
MoreSaves
Pale Court
QoL (turned off)
Toggleable Bindings
[as well as all of their dependencies ofc!]

**Comment by AbsoluteStratos** [comment]
Ah I see, I pushed an update that attempts to reset the materials on the particles dynamically. Not a guaranteed fix but maybe it will work since it works with the sprites. I havent figured out a good way to test other OS's yet so I'm only testing windows atm.

Give the updated version (1.0.1) a go.

Tbh I'm surprised it loads at all lol

**Comment by MagmaFang23** [comment]
just tried it. the particles show up now!
